// Thailand NYE — Data Model v2
// 13 spots reclassified, research layer filled, personal layer blank for Brady

export default {
  id: 'thailand',
  name: 'Thailand NYE',
  region: 'Southeast Asia',
  route: '/thailand',
  tagline: 'Bangkok, Koh Phangan, Krabi. Built around New Year\'s Eve at Haad Rin.',
  confidence: 'Research-Based',
  heroStats: [
    { value: 'Dec 26', label: 'Arrival' },
    { value: 'NYE', label: 'Haad Rin Anchor' },
    { value: '4-8', label: 'Group Size' },
  ],

  palette: {
    bg: '#0e0e0c',
    surface: '#181814',
    elevated: '#222220',
    accent: '#c9a84c',
  },

  overview: {
    quickRead: 'The entire trip is built around one fixed point: Haad Rin Beach on December 31. Bangkok on arrival, ferry to Koh Phangan for NYE, then south to Krabi for beaches and recovery. Seven days, three locations, one anchor event.',
    budget: '$1,153-$1,561 lean to $1,706-$2,340 generous. All-in from ORD.',
    framework: 'Built from research across multiple sources. The itinerary is structured around the NYE Full Moon Party at Haad Rin, which dictates the timing of every other segment. Not yet personally validated.',
    philosophy: 'Thailand rewards the group that picks a base in each location and explores from there. Do not island-hop every day. Bangkok is chaos by design. Koh Phangan is the anchor. Krabi is the cooldown.',
  },

  timingWindows: [
    { id: 'nye', name: 'NYE Window (Dec 26 - Jan 2)', recommended: true, atmosphere: 'Peak party, warm, dry season', crowdMix: '70% tourist', pubExperience: 'Full Moon Party + NYE combined', priceTier: 'High', primaryDraw: 'NYE Full Moon Party', verdict: 'The anchor event', detail: 'Dry season. 28-32°C. Haad Rin NYE is the defining event. Book domestic flights and ferries months ahead — NYE routes sell out. Accommodation near Haad Rin is 3x normal.' },
    { id: 'shoulder', name: 'Nov or Jan (non-NYE)', recommended: true, atmosphere: 'Warm, less crowded', crowdMix: '50/50', pubExperience: 'Regular Full Moon Party', priceTier: 'Moderate', primaryDraw: 'Same beaches, half the price', verdict: 'Better value if NYE isn\'t mandatory', detail: 'Same weather, same islands, dramatically lower prices. Regular Full Moon Party still happens monthly. Koh Phangan accommodation drops 50-70%.' },
  ],

  itinerary: [
    { day: 'Day 1-2', anchor: 'Bangkok', stops: 'Grand Palace + Wat Pho morning, Chinatown street food evening, Khao San one night' },
    { day: 'Day 3', anchor: 'Travel to Koh Phangan', stops: 'BKK-KSM flight, Lomprayah ferry to Koh Phangan, settle in Ban Tai' },
    { day: 'Day 4', anchor: 'Koh Phangan', stops: 'Bottle Beach by longtail boat, recovery day' },
    { day: 'Day 5', anchor: 'NYE at Haad Rin', stops: 'Pre-game Ban Tai, songthaew to Haad Rin, Full Moon NYE Party all night' },
    { day: 'Day 6', anchor: 'Travel to Krabi', stops: 'Ferry + bus/flight to Krabi, Railay Beach afternoon' },
    { day: 'Day 7', anchor: 'Krabi + Departure', stops: 'Tiger Cave Temple sunrise, Hong Islands day trip, depart' },
  ],

  // ===== V2 SPOTS — RECLASSIFIED WITH RESEARCH LAYER =====
  spots: [
    // ── BANGKOK ──
    {
      name: 'Grand Palace', city: 'Bangkok', neighborhood: 'Rattanakosin',
      category: 'Historical Site', subcategory: 'Royal palace complex',
      vibeTags: ['Take It All In', 'Show Them Everything'],
      description: 'The most visited site in Bangkok. Dress code enforced — long pants, covered shoulders. Go at 8:30am opening to beat the crowds. Watch for the "Grand Palace is closed" scam — tuk-tuk drivers will try to redirect you to gem shops.',
      priceRange: '$$', hours: 'Daily 8:30am-3:30pm',
      happyHour: 'N/A', wayToSave: '500 THB entry (~$14). Combine with Wat Pho (adjacent) in one morning. Cross to Wat Arun by 4 THB ferry.',
      bestTime: 'morning', address: 'Na Phra Lan Road, Phra Nakhon, Bangkok 10200',
      coordinates: { lat: 13.7503, lng: 100.4912 }, website: 'https://www.royalgrandpalace.th',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: true, photoKey: '',
    },
    {
      name: 'Wat Pho', city: 'Bangkok', neighborhood: 'Rattanakosin',
      category: 'Religious / Spiritual', subcategory: 'Buddhist temple',
      vibeTags: ['Take It All In', 'Show Them Everything'],
      description: 'Reclining Buddha — 46 meters long, covered in gold leaf. Adjacent to the Grand Palace. Worth combining into one morning. Also home to Thailand\'s oldest massage school.',
      priceRange: '$', hours: 'Daily 8am-7:30pm',
      happyHour: 'N/A', wayToSave: '200 THB entry (~$6). Thai massage on-site 260 THB/30min — legitimate and cheap.',
      bestTime: 'morning', address: '2 Sanam Chai Road, Phra Nakhon, Bangkok 10200',
      coordinates: { lat: 13.7462, lng: 100.4930 }, website: 'https://www.watpho.com',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
    {
      name: 'Wat Arun', city: 'Bangkok', neighborhood: 'Thonburi',
      category: 'Religious / Spiritual', subcategory: 'Buddhist temple',
      vibeTags: ['Take It All In', 'Show Them Everything'],
      description: 'Temple of Dawn. Cross the river by ferry from Wat Pho (4 THB). Best photographed from the east bank at sunset, best visited in person in the morning. Climb the central prang for river views.',
      priceRange: '$', hours: 'Daily 8am-6pm',
      happyHour: 'N/A', wayToSave: '100 THB entry (~$3). 4 THB ferry from Wat Pho pier. The cheapest river crossing in Bangkok.',
      bestTime: 'morning', address: '158 Wang Doem Road, Bangkok Yai, Bangkok 10600',
      coordinates: { lat: 13.7438, lng: 100.4889 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
    {
      name: 'Rajadamnern Muay Thai', city: 'Bangkok', neighborhood: 'Phra Nakhon',
      category: 'Activity / Tour', subcategory: 'Muay Thai stadium',
      vibeTags: ['Send It', 'Show Them Everything', 'Push Your Limits'],
      description: 'The original Muay Thai stadium. Fights most evenings from ~8pm. Real sport, not a tourist show. Ringside seats available. The atmosphere is electric.',
      priceRange: '$$', hours: 'Events daily, doors ~6pm, fights from ~8pm',
      happyHour: 'N/A', wayToSave: 'Ringside seats 1,500-2,000 THB (~$43-57). Standard seats cheaper. Book online.',
      bestTime: 'evening', address: '8 Rajadamnern Nok Road, Bangkok 10100',
      coordinates: { lat: 13.7567, lng: 100.5053 }, website: 'https://rajadamnern.com',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
    {
      name: 'Khao San Road', city: 'Bangkok', neighborhood: 'Banglamphu',
      category: 'Neighborhood', subcategory: 'Backpacker strip',
      vibeTags: ['Send It', 'Show Them Everything'],
      description: 'The backpacker strip. Worth one evening for the spectacle — street food, cheap drinks, chaos. Not worth a second visit. The adjacent Rambuttri Road is better.',
      priceRange: '$', hours: 'Bars open until 2am+',
      happyHour: 'Drink specials everywhere — buckets 100-200 THB', wayToSave: 'Already the cheapest drinking in Bangkok. Buckets (mixed drinks) 100-200 THB. One evening is enough.',
      bestTime: 'evening', address: 'Khao San Road, Banglamphu, Bangkok',
      coordinates: { lat: 13.7589, lng: 100.4974 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
    {
      name: 'Chinatown / Yaowarat', city: 'Bangkok', neighborhood: 'Samphanthawong',
      category: 'Neighborhood', subcategory: 'Street food district',
      vibeTags: ['Take It All In', 'Show Them Everything'],
      description: 'The best street food corridor in Bangkok. Go at night when the stalls open along Yaowarat Road. This is where locals eat. Pad Thai, roasted duck, mango sticky rice — all under 100 THB.',
      priceRange: '$', hours: 'Night market stalls open ~5pm-midnight',
      happyHour: 'N/A', wayToSave: 'Dishes 40-100 THB ($1-3). You can eat a full dinner for under $5. Follow the locals, not the neon signs.',
      bestTime: 'evening', address: 'Yaowarat Road, Samphanthawong, Bangkok',
      coordinates: { lat: 13.7400, lng: 100.5080 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: true, photoKey: '',
    },
    {
      name: 'Terminal 21 Food Court', city: 'Bangkok', neighborhood: 'Asok',
      category: 'Quick Bites', subcategory: 'Mall food court',
      vibeTags: ['Just Us'],
      description: 'Mall food court (Pier 21, 5th floor) with full Thai meals for 60-100 THB ($1.70-$2.85). Not a tourist trap — locals eat here daily. Air-conditioned lunch stop between temples.',
      priceRange: '$', hours: 'Daily 10am-10pm',
      happyHour: 'N/A', wayToSave: 'Already absurdly cheap. Buy a food court card, load 200 THB, eat like a king. Refund unused balance at the counter.',
      bestTime: 'afternoon', address: '88 Sukhumvit Soi 19, Bangkok 10110',
      coordinates: { lat: 13.7376, lng: 100.5601 }, website: 'https://www.terminal21.co.th',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },

    // ── KOH PHANGAN ──
    {
      name: 'Ban Tai (Base)', city: 'Koh Phangan', neighborhood: 'West Coast',
      category: 'Neighborhood', subcategory: 'Budget base area',
      vibeTags: ['Just Us', 'Unplug'],
      description: 'Base here, NOT Haad Rin. $240/person cheaper for accommodation, quieter between events, and 20 minutes by songthaew to Haad Rin on NYE. Every dollar saved on a room is a dollar spent on the experience.',
      priceRange: '$', hours: 'Always accessible',
      happyHour: 'N/A', wayToSave: '$240/person saved vs Haad Rin. Songthaew to Haad Rin 150-200 THB on NYE.',
      bestTime: 'any', address: 'Ban Tai, Ko Pha-ngan, Surat Thani',
      coordinates: { lat: 9.7200, lng: 100.0200 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
    {
      name: 'Haad Rin NYE', city: 'Koh Phangan', neighborhood: 'Southeast Tip',
      category: 'Activity / Tour', subcategory: 'Beach party',
      vibeTags: ['Send It', 'Show Them Everything'],
      description: 'The Full Moon Party on December 31. 30,000+ people on the beach. Free entry — no ticket required. Anyone selling "NYE tickets" is scamming you. Fire shows, DJs, bars along the entire beachfront.',
      priceRange: 'Free', hours: 'Sunset to sunrise',
      happyHour: 'Buckets (mixed drinks) 200-350 THB at beach bars', wayToSave: 'Free entry. Buckets from beach bars 200-350 THB. Buy from the main bars, not random sellers. Watch your drinks.',
      bestTime: 'evening', address: 'Haad Rin Nok, Ko Pha-ngan, Surat Thani 84280',
      coordinates: { lat: 9.6725, lng: 100.0582 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: true, photoKey: '',
    },
    {
      name: 'Bottle Beach', city: 'Koh Phangan', neighborhood: 'North Coast',
      category: 'Natural Wonder', subcategory: 'Beach',
      vibeTags: ['Unplug', 'Just Us'],
      description: 'Only accessible by boat. One of the most beautiful beaches on the island. Longtail boat from Chaloklum. Recovery day destination after NYE.',
      priceRange: '$', hours: 'Always accessible. Longtail boats from Chaloklum ~8am-5pm',
      happyHour: 'N/A', wayToSave: 'Longtail boat 150-200 THB/person from Chaloklum. Share with other travelers to split cost.',
      bestTime: 'morning', address: 'Bottle Beach, Ko Pha-ngan',
      coordinates: { lat: 9.7800, lng: 100.0400 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },

    // ── KRABI ──
    {
      name: 'Railay Beach', city: 'Krabi', neighborhood: 'Railay Peninsula',
      category: 'Natural Wonder', subcategory: 'Beach',
      vibeTags: ['Unplug', 'Take It All In'],
      description: 'Only accessible by longtail boat. Limestone cliffs, clear water, rock climbing. The single best beach in mainland Thailand. Stay one night if budget allows.',
      priceRange: '$', hours: 'Always accessible. Boats from Ao Nang 8am-6pm, 100 THB/person',
      happyHour: 'N/A', wayToSave: 'Longtail from Ao Nang 100 THB/person (15 min). Stay at Railay for one night to justify the boat fare.',
      bestTime: 'morning', address: 'Railay, Mueang Krabi, Krabi Province',
      coordinates: { lat: 8.0126, lng: 98.8372 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: true, photoKey: '',
    },
    {
      name: 'Hong Islands', city: 'Krabi', neighborhood: 'Ao Nang',
      category: 'Activity / Tour', subcategory: 'Island day trip',
      vibeTags: ['Take It All In', 'Show Them Everything'],
      description: 'Day trip by longtail or speedboat from Ao Nang. Lagoon surrounded by karst cliffs. Snorkeling, kayaking, emerald water. Book the morning trip to avoid afternoon crowds.',
      priceRange: '$$', hours: 'Tours depart 8-9am, return 3-4pm',
      happyHour: 'N/A', wayToSave: 'Group longtail (1,500-2,500 THB/boat) is cheaper than speedboat tours. Split with other travelers.',
      bestTime: 'morning', address: 'Ao Nang, Krabi Province',
      coordinates: { lat: 8.0800, lng: 98.7700 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
    {
      name: 'Tiger Cave Temple', city: 'Krabi', neighborhood: 'Krabi Town',
      category: 'Religious / Spiritual', subcategory: 'Buddhist temple / hike',
      vibeTags: ['Push Your Limits', 'Take It All In'],
      description: '1,237 steps to the summit. Panoramic views of Krabi and the Andaman coast. Go at sunrise to avoid heat. Monkeys at the base will take anything not secured.',
      priceRange: 'Free', hours: 'Daily 5am-6pm',
      happyHour: 'N/A', wayToSave: 'Free entry. Bring water and secure all belongings from monkeys. Sunrise is cooler and less crowded.',
      bestTime: 'morning', address: 'Huai Nam Khao, Krabi 81120',
      coordinates: { lat: 8.1128, lng: 98.9232 }, website: '',
      ladsTake: '', story: '', forWho: '',
      validated: true, validator: 'Research', visitDate: '', featured: false, photoKey: '',
    },
  ],

  // ===== LEGACY CATEGORIES =====
  categories: [
    { name: 'Bangkok Attractions', id: 'bangkok', spots: [] },
    { name: 'Koh Phangan', id: 'koh-phangan', spots: [] },
    { name: 'Krabi', id: 'krabi', spots: [] },
  ],

  dayTrips: [],

  mapsLinks: [],

  logistics: {
    flights: 'Cathay Pacific ORD-HKG-BKK $800-986 round trip. Book domestic flight BKK-KSM (Koh Samui, then ferry to Koh Phangan) at the same time as international — $40-80 one way. Do not book domestic flights late; NYE routes sell out.',
    inCountry: 'BKK-KSM domestic flight $40-80, then Lomprayah ferry to Koh Phangan. Koh Phangan to Krabi: ferry + bus combo or domestic flight via Surat Thani.',
    gettingAround: 'Bangkok: BTS Skytrain + MRT for main areas, Grab (not Uber) for taxis, longtail boats on the river. Koh Phangan: rent a scooter ONLY if experienced — roads are steep and unpaved in places. Songthaew (shared trucks) are the safe default. Krabi: longtail boats to Railay, songthaew between beaches.',
    tipping: 'Not expected in most places. 20-50 THB for exceptional service. Round up in nicer restaurants.',
  },

  costModel: {
    headers: ['Category', 'Lean', 'Generous'],
    rows: [
      ['Flights (ORD-BKK)', '$800', '$986'],
      ['Domestic Flight (BKK-KSM)', '$40', '$80'],
      ['Accommodation (7 nights)', '$140', '$490'],
      ['Food & Drink', '$70', '$210'],
      ['Activities & Boats', '$50', '$150'],
      ['Local Transit', '$30', '$70'],
      ['Ferries', '$23', '$54'],
    ],
    totals: ['All-In Total', '~$1,153-$1,561', '~$1,706-$2,340'],
    lean: '$1,153 floor assumes hostels, street food, minimal activities. $1,561 lean-comfortable with private rooms and one paid excursion per location.',
  },

  mistakes: [
    { title: 'Staying in Haad Rin', detail: 'Accommodation in Haad Rin over NYE is $240/person more expensive than Ban Tai, 20 minutes away. You are paying a premium to sleep next to a sound system.' },
    { title: 'Buying Fake NYE Tickets', detail: 'There is no ticket to the Haad Rin Full Moon Party. Entry to the beach is free. Anyone selling tickets — online or in person — is running a scam.' },
    { title: 'Renting a Scooter Without Experience', detail: 'Koh Phangan roads are steep, unpaved in sections, and shared with trucks. If you have never ridden a motorbike, this is not the place to learn. Songthaew is the safe option.' },
    { title: 'Eating on the Tourist Strip', detail: 'Tourist-facing restaurants charge 3-5x local prices. Yaowarat in Bangkok and market stalls everywhere else serve better food for a fraction of the cost.' },
    { title: 'Choosing USD at ATMs', detail: 'When a Thai ATM asks "charge in USD or THB?" — always choose THB. Choosing USD triggers a 5-8% dynamic currency conversion fee on top of the ATM withdrawal fee.' },
    { title: 'Booking Domestic Flights Late', detail: 'BKK-KSM flights over NYE sell out and prices triple. Book domestic and international flights at the same time.' },
    { title: 'Grand Palace Redirect Scam', detail: 'Tuk-tuk drivers near the Grand Palace will tell you it is closed and offer to take you to a "better temple" (which leads to a gem shop kickback). The Grand Palace is open. Walk past them.' },
  ],

  ladsTake: 'The entire trip is built around one fixed point: Haad Rin Beach on December 31.',

  specialCallouts: [
    { type: 'savings', title: 'Ban Tai vs Haad Rin — $240/Person Saved', text: 'Ban Tai on the west coast is 20 minutes from Haad Rin by songthaew. Accommodation runs $240/person cheaper over the NYE window. Quieter base, same party access. The savings alone cover two days of food and activities.' },
    { type: 'warning', title: 'NYE Ticket Scam', text: 'The Haad Rin Full Moon Party has no entry fee. There is no ticket. Websites and street vendors selling "VIP NYE passes" or "Full Moon Party tickets" are scams. Entry to the beach is free — always has been.' },
  ],

  navSections: ['Overview', 'Bangkok', 'Koh Phangan', 'Krabi', 'Costs', 'Safety'],
};
