#!/usr/bin/env node
/**
 * Airtable -> src/data/ sync script
 * Run: node scripts/airtable-sync.js
 * Pulls all spots from Airtable, generates JS data modules per destination
 */

import Airtable from 'airtable'
import fs from 'fs'
import path from 'path'
import dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const base = new Airtable({ apiKey: process.env.AIRTABLE_API_KEY })
  .base(process.env.AIRTABLE_BASE_ID)

async function sync() {
  console.log('Fetching spots from Airtable...')
  const records = []

  await base('Spots').select({
    pageSize: 100,
    sort: [{ field: 'name', direction: 'asc' }]
  }).eachPage((pageRecords, fetchNext) => {
    records.push(...pageRecords.map(r => r.fields))
    fetchNext()
  })

  console.log(`Fetched ${records.length} spots`)

  const byFramework = {}
  records.forEach(spot => {
    const contexts = spot.contexts || []
    const frameworkContext = contexts.find(c => c.startsWith('city-framework:'))
    if (frameworkContext) {
      const framework = frameworkContext.replace('city-framework:', '')
      if (!byFramework[framework]) byFramework[framework] = []
      byFramework[framework].push(spot)
    }
  })

  Object.entries(byFramework).forEach(([framework, spots]) => {
    const outPath = path.join('src', 'data', `${framework}.js`)
    const content = `// Auto-generated by airtable-sync.js — do not edit manually
// Last synced: ${new Date().toISOString()}
// Source: Airtable base ${process.env.AIRTABLE_BASE_ID}

export const spots = ${JSON.stringify(spots, null, 2)}

export const meta = {
  destination: '${framework}',
  spotCount: ${spots.length},
  lastSynced: '${new Date().toISOString()}',
}
`
    fs.writeFileSync(outPath, content)
    console.log(`  ${framework}: ${spots.length} spots -> ${outPath}`)
  })

  console.log('Sync complete.')
}

sync().catch(console.error)
