#!/usr/bin/env node
/**
 * Airtable -> src/data/ sync script
 * Run: node scripts/airtable-sync.js
 * Pulls all spots from Airtable, generates JS data modules per destination
 */

import fs from 'fs'
import path from 'path'
import dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const API_KEY = process.env.AIRTABLE_API_KEY
const BASE_ID = process.env.AIRTABLE_BASE_ID
const TABLE_ID = 'tblL3pWmvThTBO6gi'
const BASE_URL = `https://api.airtable.com/v0/${BASE_ID}/${TABLE_ID}`

async function fetchAllRecords() {
  const records = []
  let offset = null

  do {
    const url = new URL(BASE_URL)
    url.searchParams.set('pageSize', '100')
    if (offset) url.searchParams.set('offset', offset)

    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${API_KEY}` }
    })

    if (!res.ok) {
      const err = await res.json()
      throw new Error(`Airtable API error ${res.status}: ${err.error?.message || JSON.stringify(err)}`)
    }

    const data = await res.json()
    records.push(...data.records.map(r => r.fields))
    offset = data.offset
  } while (offset)

  return records
}

async function sync() {
  console.log('Fetching spots from Airtable...')
  const records = await fetchAllRecords()
  console.log(`Fetched ${records.length} spots`)

  // Group by Country for now (Airtable has City as a linked record ID)
  const byCountry = {}
  records.forEach(spot => {
    const country = spot.Country || 'unknown'
    if (!byCountry[country]) byCountry[country] = []
    byCountry[country].push(spot)
  })

  Object.entries(byCountry).forEach(([country, spots]) => {
    const slug = country.toLowerCase().replace(/\s+/g, '-')
    const outPath = path.join('src', 'data', `airtable-${slug}.js`)
    const content = `// Auto-generated by airtable-sync.js — do not edit manually
// Last synced: ${new Date().toISOString()}
// Source: Airtable base ${BASE_ID}

export const spots = ${JSON.stringify(spots, null, 2)}

export const meta = {
  country: '${country}',
  spotCount: ${spots.length},
  lastSynced: '${new Date().toISOString()}',
}
`
    fs.writeFileSync(outPath, content)
    console.log(`  ${country}: ${spots.length} spots -> ${outPath}`)
  })

  console.log('Sync complete.')
}

sync().catch(console.error)
