#!/usr/bin/env node
/**
 * Extract base64 images from JS modules → WebP files in /public/images/
 * Generates src/images-paths.js with path references.
 * Run: node scripts/extract-images.js
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const MODULES = [
  { file: 'src/images.js', exportName: 'IMAGES', dir: 'images' },
  { file: 'src/images-new.js', exportName: 'NEW_IMAGES', dir: 'images-new' },
  { file: 'src/images-batch3.js', exportName: 'BATCH3_IMAGES', dir: 'images-batch3' },
  { file: 'src/images-batch4.js', exportName: 'BATCH4_IMAGES', dir: 'images-batch4' },
  { file: 'src/images-hero.js', exportName: 'HERO_IMAGES', dir: 'images-hero' },
  { file: 'src/images-heic-hero.js', exportName: 'HEIC_HERO_IMAGES', dir: 'images-heic-hero' },
  { file: 'src/images-heic-card.js', exportName: 'HEIC_CARD_IMAGES', dir: 'images-heic-card' },
];

const MAX_WIDTH = 1400;
const WEBP_QUALITY = 82;
const OUTPUT_BASE = path.join(process.cwd(), 'public', 'images');

function parseBase64Module(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const entries = {};
  // Match patterns like: keyName: 'data:image/...' or keyName: "data:image/..."
  const regex = /(\w+)\s*:\s*['"`](data:image\/[^;]+;base64,[^'"`]+)['"`]/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    entries[match[1]] = match[2];
  }
  return entries;
}

async function processImage(key, dataUri, outputDir) {
  const base64Match = dataUri.match(/^data:image\/(\w+);base64,(.+)$/);
  if (!base64Match) return null;

  const buffer = Buffer.from(base64Match[2], 'base64');
  const originalSize = buffer.length;

  fs.mkdirSync(outputDir, { recursive: true });
  const outPath = path.join(outputDir, `${key}.webp`);

  let pipeline = sharp(buffer).webp({ quality: WEBP_QUALITY });

  // Resize if wider than MAX_WIDTH
  const metadata = await sharp(buffer).metadata();
  if (metadata.width > MAX_WIDTH) {
    pipeline = sharp(buffer).resize(MAX_WIDTH).webp({ quality: WEBP_QUALITY });
  }

  await pipeline.toFile(outPath);
  const newSize = fs.statSync(outPath).size;

  return { originalSize, newSize };
}

async function main() {
  let totalOriginal = 0;
  let totalNew = 0;
  let totalCount = 0;
  const pathExports = {};

  for (const mod of MODULES) {
    const filePath = path.join(process.cwd(), mod.file);
    if (!fs.existsSync(filePath)) {
      console.log(`  SKIP: ${mod.file} not found`);
      continue;
    }

    console.log(`\nProcessing ${mod.file} (${mod.exportName})...`);
    const entries = parseBase64Module(filePath);
    const keys = Object.keys(entries);
    console.log(`  Found ${keys.length} images`);

    const outputDir = path.join(OUTPUT_BASE, mod.dir);
    const modulePaths = {};

    for (const key of keys) {
      try {
        const result = await processImage(key, entries[key], outputDir);
        if (result) {
          totalOriginal += result.originalSize;
          totalNew += result.newSize;
          totalCount++;
          modulePaths[key] = `/images/${mod.dir}/${key}.webp`;
          process.stdout.write(`  ${key} (${(result.originalSize / 1024).toFixed(0)}KB → ${(result.newSize / 1024).toFixed(0)}KB)\n`);
        }
      } catch (err) {
        console.error(`  ERROR processing ${key}: ${err.message}`);
      }
    }

    pathExports[mod.exportName] = modulePaths;
  }

  // Generate images-paths.js
  let pathsFile = '// Auto-generated by scripts/extract-images.js — do not edit manually\n';
  pathsFile += `// Generated: ${new Date().toISOString()}\n`;
  pathsFile += `// ${totalCount} images extracted\n\n`;

  for (const [exportName, paths] of Object.entries(pathExports)) {
    pathsFile += `export const ${exportName} = {\n`;
    for (const [key, p] of Object.entries(paths)) {
      pathsFile += `  ${key}: '${p}',\n`;
    }
    pathsFile += '};\n\n';
  }

  fs.writeFileSync(path.join(process.cwd(), 'src', 'images-paths.js'), pathsFile);

  console.log('\n=== EXTRACTION COMPLETE ===');
  console.log(`Total images: ${totalCount}`);
  console.log(`Original total: ${(totalOriginal / 1024 / 1024).toFixed(1)} MB`);
  console.log(`New total:      ${(totalNew / 1024 / 1024).toFixed(1)} MB`);
  console.log(`Compression:    ${((1 - totalNew / totalOriginal) * 100).toFixed(1)}% reduction`);
  console.log(`Output: public/images/ + src/images-paths.js`);
}

main().catch(console.error);
