/* PERU SILHOUETTE TRACER — emits src/data/peruGeo.js
 *
 * Same method as tools/trace-midwest.mjs, and deliberately so: fetch a real
 * boundary, simplify hard with Douglas-Peucker, then project through ONE
 * equirectangular transform that every pin, route and label also uses. A place
 * marker projected through a different transform than the coastline will sit
 * off the coast, which is the failure this shared-frame discipline prevents.
 *
 * SOURCE: Natural Earth 1:50m admin-0 countries, the same source family the
 * Ontario clip already came from. 589 raw points for Peru, simplified to ~200.
 * Natural Earth is public domain.
 *
 * WHY 1:50m AND NOT 1:110m: the 110m build of Peru is 76 points, which loses
 * the coastline entirely and reads as a blob. 10m is ~25 MB to fetch for one
 * country. 50m is the honest middle.
 *
 * REGENERATE:
 *   1. curl the Natural Earth 50m countries geojson
 *   2. node tools/trace-peru.mjs <path-to-geojson>
 */

import { readFileSync, writeFileSync } from 'fs'

const src = process.argv[2]
if (!src) {
  console.error('usage: node tools/trace-peru.mjs <ne_50m_admin_0_countries.geojson>')
  process.exit(1)
}

const geo = JSON.parse(readFileSync(src, 'utf8'))
const feature = geo.features.find(
  (f) => (f.properties.ADM0_A3 || f.properties.ISO_A3) === 'PER',
)
if (!feature) {
  console.error('Peru (PER) not found in the source')
  process.exit(1)
}

const g = feature.geometry
const rings = g.type === 'Polygon' ? g.coordinates : g.coordinates.flat()

/* Keep the mainland only. Peru's smaller rings are offshore islands; the
 * Midwest tracer dropped islands for the same reason — at this scale they are
 * single pixels that read as artefacts, not geography. */
const mainland = rings.reduce((a, b) => (a.length >= b.length ? a : b))

/* ---- Douglas-Peucker ---- */
function perpDist(p, a, b) {
  const [px, py] = p
  const [ax, ay] = a
  const [bx, by] = b
  const dx = bx - ax
  const dy = by - ay
  if (dx === 0 && dy === 0) return Math.hypot(px - ax, py - ay)
  const t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
  const cx = ax + t * dx
  const cy = ay + t * dy
  return Math.hypot(px - cx, py - cy)
}

function dp(points, eps) {
  if (points.length < 3) return points
  let maxD = 0
  let idx = 0
  for (let i = 1; i < points.length - 1; i++) {
    const d = perpDist(points[i], points[0], points[points.length - 1])
    if (d > maxD) {
      maxD = d
      idx = i
    }
  }
  if (maxD <= eps) return [points[0], points[points.length - 1]]
  return [...dp(points.slice(0, idx + 1), eps).slice(0, -1), ...dp(points.slice(idx), eps)]
}

/* Binary-search the tolerance that lands nearest the target point count. The
 * Midwest tracer tuned tolerance by hand; searching it means a re-trace at a
 * different target does not need a human to re-guess. */
function simplifyTo(ring, target) {
  let lo = 0
  let hi = 5
  let best = ring
  for (let i = 0; i < 40; i++) {
    const mid = (lo + hi) / 2
    const out = dp(ring, mid)
    if (out.length > target) lo = mid
    else {
      best = out
      hi = mid
    }
  }
  return best
}

const simplified = simplifyTo(mainland, 200)

/* ---- Projection: equirectangular, one shared transform ---- */
const lats = simplified.map((p) => p[1])
const lons = simplified.map((p) => p[0])
const minLat = Math.min(...lats)
const maxLat = Math.max(...lats)
const minLon = Math.min(...lons)
const maxLon = Math.max(...lons)

const lat0 = (minLat + maxLat) / 2
const K = Math.cos((lat0 * Math.PI) / 180)

const PAD = 24
const spanX = (maxLon - minLon) * K
const spanY = maxLat - minLat
const VIEW_H = 1000
const scale = (VIEW_H - PAD * 2) / spanY
const VIEW_W = Math.round(spanX * scale + PAD * 2)

/* NOTE THE ARGUMENT ORDER: project(lat, lng). Data files store lat first, and
 * the Midwest tracer's internal order is GeoJSON (lon, lat). Mixing them is the
 * documented trap; this exported helper takes (lat, lng) to match the data. */
const projectLL = (lat, lng) => ({
  x: PAD + (lng - minLon) * K * scale,
  y: PAD + (maxLat - lat) * scale,
})

const d =
  simplified
    .map((p, i) => {
      const { x, y } = projectLL(p[1], p[0])
      return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`
    })
    .join('') + 'Z'

const out = `/* GENERATED by tools/trace-peru.mjs — do not hand-edit.
 *
 * Peru mainland silhouette, traced from Natural Earth 1:50m admin-0 countries
 * (public domain), simplified with Douglas-Peucker from ${mainland.length} points to
 * ${simplified.length}, and projected through ONE equirectangular transform.
 *
 *   viewBox   0 0 ${VIEW_W} ${VIEW_H}
 *   lat0      ${lat0.toFixed(3)}  (cos = ${K.toFixed(4)})
 *   scale     ${scale.toFixed(3)} px/deg
 *   bounds    lon ${minLon.toFixed(3)}..${maxLon.toFixed(3)}, lat ${minLat.toFixed(3)}..${maxLat.toFixed(3)}
 *
 * ⚠️ EVERY pin, route point and label on this canvas MUST be projected with
 * \`project(lat, lng)\` below. A marker placed through any other transform will
 * not sit where the coastline says it sits.
 *
 * ⚠️ ARGUMENT ORDER IS (lat, lng) — data files store lat first. The tracer's
 * own internal order is GeoJSON (lon, lat). Do not mix them.
 */

export const VIEW_BOX = '0 0 ${VIEW_W} ${VIEW_H}'
export const VIEW_W = ${VIEW_W}
export const VIEW_H = ${VIEW_H}

export const PROJECTION = {
  lat0: ${lat0},
  K: ${K},
  scale: ${scale},
  pad: ${PAD},
  minLon: ${minLon},
  maxLat: ${maxLat},
}

export function project(lat, lng) {
  return {
    x: PROJECTION.pad + (lng - PROJECTION.minLon) * PROJECTION.K * PROJECTION.scale,
    y: PROJECTION.pad + (PROJECTION.maxLat - lat) * PROJECTION.scale,
  }
}

export const PERU_PATH = '${d}'
`

writeFileSync('src/data/peruGeo.js', out, 'utf8')
console.log(
  `wrote src/data/peruGeo.js — ${mainland.length} -> ${simplified.length} pts, viewBox 0 0 ${VIEW_W} ${VIEW_H}`,
)
